### ISSUE TITLE
Don't see any video from Vimeo

### ISSUE THREAD

**Issue by Ibochkarev** [modxorg/Docs#10]
## Affected page(s)

https://modxdocs.mhserver.nl/current/en/getting-started/video-quick-start-series

## What needs to be improved?

Connect the player to play the video on the page

## Relevant versions

The problem affects the following version(s): 

- [x] 2.x (current)
- [ ] 3.x

**Comment by Ibochkarev** [comment]
@Mark-H For example:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#youtube-videos

**Comment by Mark-H** [comment]
I think the simplest solution is to replace it with the actual HTML to embed it. I haven't tried it with our particular markdown parser (`league/commonmark`) to see if that defaults to preventing embeds, but valid HTML should work. 

An alternative could be a plugin that identifies a vimeo/youtube link and turns it into an embed: https://gist.github.com/0b10011/9017f38586404f161298
