### ISSUE TITLE
All pages Roadmap in Extras contain old information

### ISSUE THREAD

**Issue by meshkov** [modxorg/Docs#114]
## Affected page(s)

All pages Roadmap in Extras contain old information. 
For example:
[https://docs.modx.org/current/en/extras/login/login.roadmap](url)  
[https://docs.modx.org/current/en/extras/quip/quip.roadmap](url)

## What needs to be improved?

I think we need to delete these pages. Because relevant information is contained in releases of Extras.

**Comment by Mark-H** [comment]
While deleting files might cause 404s, I think if there's nothing sensible to say on roadmap pages that it does make sense to delete or at the very least update them, perhaps to refer to github instead.

**Comment by meshkov** [comment]
@Mark-H on page [https://docs.modx.org/current/en/extras/login](https://docs.modx.org/current/en/extras/login) there is information about Development and Bug Reporting:
![image](https://user-images.githubusercontent.com/1703670/67750884-23166800-fa41-11e9-99f4-870010448ef2.png)

**Comment by ant-tar** [comment]
I'll fix them, as for me Roadmap's should be removed(let changelog relevance will be on the conscience of extra creators :) ), Github information/links should be enough
