### ISSUE TITLE
Markdown validation issues

### ISSUE THREAD

**Issue by Mark-H** [modxorg/Docs#131]
I've added a new github action but that's showing another 200 or so validation issues across 2.x that need to be resolved, before it's useful as an automatic check.  

I've already fixed a bunch, but could use some help :p 

- [x] 2019-12-06T14:34:53.8288725Z en/extending-modx/getting-started/developer-introduction.md: 53: MD001/heading-increment/header-increment Heading levels should only increment by one level at a time [Expected: h4; Actual: h5]
- [x] 2019-12-06T14:34:53.8289695Z en/extending-modx/tutorials/developing-an-extra/part-2.md: 851: MD036/no-emphasis-as-heading/no-emphasis-as-header Emphasis used instead of a heading [Context: "Note: saves about 30 bytes dis..."]
- [x] 2019-12-06T14:34:53.8290077Z en/extras/bdlistings/bdlistings.md: 18: MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "- id"]
- [x] 2019-12-06T14:34:53.8290486Z en/extras/bdlistings/bdlistings.md: 44: MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "{"city": "ASC", "neighborhood"..."]
- [x] 2019-12-06T14:34:53.8290850Z en/extras/bdlistings/bdlistings.md: 45: MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "``` |"]
- [x] 2019-12-06T14:34:53.8291218Z en/extras/bdlistings/bdlistings.md: 186: MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "``` php"]
- [x] 2019-12-06T14:34:53.8291544Z en/extras/csssweet/index.md: 42: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '.']
- [x] 2019-12-06T14:34:53.8291985Z en/extras/discuss/discuss.controllers.md: 16: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8292397Z en/extras/discuss/discuss.installation.md: 59: MD036/no-emphasis-as-heading/no-emphasis-as-header Emphasis used instead of a heading [Context: "Rewrite rules are not necessar..."]
- [x] 2019-12-06T14:34:53.8293415Z en/extras/eletters/eletters.api.md: 13: MD036/no-emphasis-as-heading/no-emphasis-as-header Emphasis used instead of a heading [Context: "Snippet Example, found at: cor..."]
- [x] 2019-12-06T14:34:53.8293795Z en/extras/eletters/index.md: 62: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8294222Z en/extras/eventmanager/eventmanager.emlistevents.md: 26: MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "- date (time, formatted with s..."]
- [x] 2019-12-06T14:34:53.8294609Z en/extras/flexibility/index.md: 64: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8295037Z en/extras/imagestyles/index.md: 11: MD036/no-emphasis-as-heading/no-emphasis-as-header Emphasis used instead of a heading [Context: "This component is developed co..."]
- [x] 2019-12-06T14:34:53.8295412Z en/extras/importx/index.md: 124: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '.']
- [x] 2019-12-06T14:34:53.8295767Z en/extras/index.md: 34: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8296173Z en/extras/lingua/index.md: 173: MD001/heading-increment/header-increment Heading levels should only increment by one level at a time [Expected: h3; Actual: h4]
- [x] 2019-12-06T14:34:53.8297068Z en/extras/lingua/index.md: 173: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8297446Z en/extras/lingua/index.md: 177: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8297760Z en/extras/lingua/index.md: 198: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8298102Z en/extras/login/login.tutorials/request-membership.md: 334: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '.']
- [x] 2019-12-06T14:34:53.8298414Z en/extras/mchimpx/index.md: 53: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8298740Z en/extras/mhpaypal/index.md: 31: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8299048Z en/extras/migx/index.md: 51: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8299807Z en/extras/migx/migx.tutorials/create-selectable-and-sortable-attributes-list-for-whatever-you-need-it.md: 25: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8300278Z en/extras/migx/migx.tutorials/create-selectable-and-sortable-attributes-list-for-whatever-you-need-it.md: 39: MD046/code-block-style Code block style [Expected: fenced; Actual: indented]
- [x] 2019-12-06T14:34:53.8300791Z en/extras/migx/migx.tutorials/create-selectable-and-sortable-attributes-list-for-whatever-you-need-it.md: 51: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8301165Z en/extras/migx/migx.tutorials/create-selectable-and-sortable-attributes-list-for-whatever-you-need-it.md: 56: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8301552Z en/extras/migx/migx.tutorials/create-selectable-and-sortable-attributes-list-for-whatever-you-need-it.md: 71: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8301936Z en/extras/migx/migx.tutorials/create-selectable-and-sortable-attributes-list-for-whatever-you-need-it.md: 77: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8302378Z en/extras/migx/migx.tutorials/fancybox-images-with-seperate-placeholders-in-richtext-content.md: 114: MD001/heading-increment/header-increment Heading levels should only increment by one level at a time [Expected: h4; Actual: h5]
- [x] 2019-12-06T14:34:53.8302719Z en/extras/migx/migx.tutorials/index.md: 11: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8303061Z en/extras/migx/migx.tutorials/sortable-resourcelist.md: 37: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8303558Z en/extras/migx/migx.tutorials/sortable-resourcelist.md: 230: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8303882Z en/extras/migx/migx.tutorials/sortable-resourcelist.md: 232: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8304217Z en/extras/migx/migx.tutorials/sortable-resourcelist.md: 236: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8304590Z en/extras/migx/migx.tutorials/use-resource-specific-media-source-and-multifile-uploader.md: 21: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8328393Z en/extras/migx/migx.tutorials/use-resource-specific-media-source-and-multifile-uploader.md: 24: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8328938Z en/extras/migx/migx.tutorials/use-resource-specific-media-source-and-multifile-uploader.md: 27: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8329398Z en/extras/migx/migx.tutorials/use-resource-specific-media-source-and-multifile-uploader.md: 38: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8329994Z en/extras/migx/migx.tutorials/use-resource-specific-media-source-and-multifile-uploader.md: 40: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8330461Z en/extras/migx/migx.tutorials/use-resource-specific-media-source-and-multifile-uploader.md: 43: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8330880Z en/extras/migx/migx.tutorials/use-resource-specific-media-source-and-multifile-uploader.md: 45: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8331299Z en/extras/migx/migx.tutorials/use-resource-specific-media-source-and-multifile-uploader.md: 51: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8331732Z en/extras/migx/migx.tutorials/use-resource-specific-mediasource-and-multifile-uploader.md: 22: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8332147Z en/extras/migx/migx.tutorials/use-resource-specific-mediasource-and-multifile-uploader.md: 25: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8332574Z en/extras/migx/migx.tutorials/use-resource-specific-mediasource-and-multifile-uploader.md: 41: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8332985Z en/extras/migx/migx.tutorials/use-resource-specific-mediasource-and-multifile-uploader.md: 43: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8333400Z en/extras/migx/migx.tutorials/use-resource-specific-mediasource-and-multifile-uploader.md: 46: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8333812Z en/extras/migx/migx.tutorials/use-resource-specific-mediasource-and-multifile-uploader.md: 48: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8334237Z en/extras/migx/migx.tutorials/use-resource-specific-mediasource-and-multifile-uploader.md: 54: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8334629Z en/extras/migx/migx.tutorials/utm-tags-for-modx/index.md: 52: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8335012Z en/extras/migx/migx.tutorials/utm-tags-for-modx/index.md: 55: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8335370Z en/extras/migx/migx.tutorials/utm-tags-for-modx/index.md: 61: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8335748Z en/extras/migx/migx.tutorials/utm-tags-for-modx/index.md: 64: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8336128Z en/extras/migx/migx.tutorials/utm-tags-for-modx/index.md: 69: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8336629Z en/extras/migx/migx.tutorials/utm-tags-for-modx/index.md: 77: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8337009Z en/extras/migx/migx.tutorials/utm-tags-for-modx/index.md: 80: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8337501Z en/extras/migxdb/migxdb.tutorials/create-a-basic-gallery-management-from-scratch-with-migxdb/add-resource-specific-mediasource-and-multifile-uploader-to-the-gallery.md: 11: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8338026Z en/extras/migxdb/migxdb.tutorials/create-a-basic-gallery-management-from-scratch-with-migxdb/add-resource-specific-mediasource-and-multifile-uploader-to-the-gallery.md: 14: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8338434Z en/extras/mxcalendar/index.md: 76: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8338827Z en/extras/mxformbuilder/index.md: 7: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8339206Z en/extras/mxformbuilder/index.md: 11: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8339960Z en/extras/mxformbuilder/mxformbuilder-create-form.md: 7: MD025/single-title/single-h1 Multiple top level headings in the same document [Context: "# Create your first form"]
- [x] 2019-12-06T14:34:53.8340392Z en/extras/mxhastvs/index.md: 9: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8340748Z en/extras/mxhastvs/index.md: 23: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8341240Z en/extras/pdoTools/Snippets/pdoNeighbors.md: 25: MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Above] [Context: "### Template Chunks"]
- [x] 2019-12-06T14:34:53.8341692Z en/extras/pdoTools/Snippets/pdoSitemap.md: 31: MD036/no-emphasis-as-heading/no-emphasis-as-header Emphasis used instead of a heading [Context: "&tpl"]
- [x] 2019-12-06T14:34:53.8342120Z en/extras/pdoTools/Snippets/pdoSitemap.md: 42: MD036/no-emphasis-as-heading/no-emphasis-as-header Emphasis used instead of a heading [Context: "&tplWrapper"]
- [x] 2019-12-06T14:34:53.8342493Z en/extras/peoples/index.md: 59: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8342836Z en/extras/peoples/index.md: 61: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8343187Z en/extras/peoples/index.md: 63: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8343547Z en/extras/peoples/peoples.md: 100: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8343902Z en/extras/peoples/peoples.md: 102: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8344264Z en/extras/peoples/peoples.md: 104: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8344613Z en/extras/peoples/peoples.peoplegroup.md: 73: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8344986Z en/extras/peoples/peoples.peoplegroup.md: 75: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8345358Z en/extras/peoples/peoples.peoplegroup.md: 77: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8345731Z en/extras/peoples/peoples.peoplegroup/usertpl.md: 32: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8346109Z en/extras/peoples/peoples.peoplegroup/usertpl.md: 34: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8346470Z en/extras/peoples/peoples.peoplegroup/usertpl.md: 36: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8346964Z en/extras/peoples/peoples.peoplegroups.md: 68: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8347335Z en/extras/peoples/peoples.peoplegroups.md: 70: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8347705Z en/extras/peoples/peoples.peoplegroups.md: 72: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8348085Z en/extras/peoples/peoples.peoplegroups/tpl.md: 30: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8348443Z en/extras/peoples/peoples.peoplegroups/tpl.md: 32: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8348814Z en/extras/peoples/peoples.peoplegroups/tpl.md: 34: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8349174Z en/extras/peoples/peoples/tpl.md: 38: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8349544Z en/extras/peoples/peoples/tpl.md: 40: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8349900Z en/extras/peoples/peoples/tpl.md: 42: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8350364Z en/extras/php-tidy-(plugin)/index.md: 14: MD025/single-title/single-h1 Multiple top level headings in the same document [Context: "# HTML 5"]
- [x] 2019-12-06T14:34:53.8350806Z en/extras/php-tidy-(plugin)/index.md: 20: MD025/single-title/single-h1 Multiple top level headings in the same document [Context: "# UTF 8"]
- [x] 2019-12-06T14:34:53.8351198Z en/extras/quip/quip.roadmap.md: 69: MD034/no-bare-urls Bare URL used [Context: "http://"]
- [x] 2019-12-06T14:34:53.8351557Z en/extras/quip/quip.roadmap.md: 75: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8351908Z en/extras/quip/quip.roadmap.md: 92: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8352331Z en/extras/sekfancybox/index.md: 113: MD001/heading-increment/header-increment Heading levels should only increment by one level at a time [Expected: h3; Actual: h4]
- [x] 2019-12-06T14:34:53.8352750Z en/extras/simplesearch/simplesearch.simplesearchform.md: 66: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8353163Z en/extras/simplesearch/simplesearch.simplesearchform.md: 76: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8353590Z en/extras/sitemapfriend/index.md: 129: MD036/no-emphasis-as-heading/no-emphasis-as-header Emphasis used instead of a heading [Context: "Available placeholders"]
- [x] 2019-12-06T14:34:53.8354012Z en/extras/sitemapfriend/index.md: 179: MD036/no-emphasis-as-heading/no-emphasis-as-header Emphasis used instead of a heading [Context: "Default Value"]
- [x] 2019-12-06T14:34:53.8354381Z en/extras/subscribeme/index.md: 41: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '.']
- [x] 2019-12-06T14:34:53.8354791Z en/extras/wayfinder/wayfinder-introductory-examples.md: 49: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8355197Z en/extras/wayfinder/wayfinder-introductory-examples.md: 55: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8355609Z en/extras/wayfinder/wayfinder-introductory-examples.md: 104: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8356010Z en/extras/wayfinder/wayfinder-introductory-examples.md: 167: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8356414Z en/extras/wayfinder/wayfinder-introductory-examples.md: 223: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8356800Z en/extras/wayfinder/wayfinder-introductory-examples.md: 239: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8357318Z en/extras/wayfinder/wayfinder-introductory-examples.md: 301: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8357696Z en/getting-started/directory-structure.md: 149: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8358099Z en/getting-started/friendly-urls/lighttpd.md: 7: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '.']
- [x] 2019-12-06T14:34:53.8358509Z en/getting-started/installation/troubleshooting.md: 126: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '.']
- [x] 2019-12-06T14:34:53.8358897Z en/getting-started/maintenance/upgrading/troubleshooting.md: 23: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '.']
- [x] 2019-12-06T14:34:53.8359326Z ru/building-sites/client-proofing/security/policies/index.md: 80: MD005/list-indent Inconsistent indentation for list items at the same level [Expected: 4; Actual: 6]
- [x] 2019-12-06T14:34:53.8359770Z ru/building-sites/client-proofing/security/policies/index.md: 81: MD005/list-indent Inconsistent indentation for list items at the same level [Expected: 4; Actual: 6]
- [x] 2019-12-06T14:34:53.8360256Z ru/building-sites/client-proofing/security/policies/index.md: 81: MD029/ol-prefix Ordered list item prefix [Expected: 1; Actual: 2; Style: 1/1/1]
- [x] 2019-12-06T14:34:53.8360694Z ru/building-sites/client-proofing/security/policies/index.md: 82: MD029/ol-prefix Ordered list item prefix [Expected: 1; Actual: 2; Style: 1/1/1]
- [x] 2019-12-06T14:34:53.8361092Z ru/building-sites/client-proofing/security/policies/index.md: 83: MD029/ol-prefix Ordered list item prefix [Expected: 1; Actual: 3; Style: 1/1/1]
- [x] 2019-12-06T14:34:53.8361485Z ru/building-sites/elements/template-variables/input-types/index.md: 54: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8361901Z ru/building-sites/elements/template-variables/step-by-step.md: 62: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '.']
- [x] 2019-12-06T14:34:53.8362288Z ru/building-sites/i18n/index.md: 15: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8362692Z ru/building-sites/resources/symlink/using-resource-symlinks.md: 15: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8363095Z ru/building-sites/tag-syntax/output-filters/custom.md: 200: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8363466Z ru/contribute/code/development-environments.md: 36: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8363874Z ru/extending-modx/creating-components/component-structure/index.md: 63: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8364270Z ru/extending-modx/creating-components/index.md: 10: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8364670Z ru/extending-modx/creating-components/work-logic/index.md: 86: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8365062Z ru/extending-modx/developing-restful-api.md: 55: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8365439Z ru/extending-modx/developing-restful-api.md: 66: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8365847Z ru/extending-modx/getting-started/developer-introduction.md: 50: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '.']
- [x] 2019-12-06T14:34:53.8366228Z ru/extending-modx/plugins.md: 49: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8366596Z ru/extending-modx/plugins.md: 93: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
- [x] 2019-12-06T14:34:53.8366965Z ru/extending-modx/snippets.md: 133: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '.']
- [x] 2019-12-06T14:34:53.8367442Z ru/extending-modx/snippets.md: 158: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '.']
- [x] 2019-12-06T14:34:53.8367815Z ru/extending-modx/snippets/accessing-tvs.md: 68: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8368194Z ru/extending-modx/snippets/accessing-tvs.md: 77: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8368548Z ru/extras/index.md: 33: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8368893Z ru/extras/migx/index.md: 50: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8369247Z ru/extras/migx/migx.tutorials/index.md: 11: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8369627Z ru/extras/migx/migx.tutorials/utm-tags-for-modx/index.md: 52: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8370016Z ru/extras/migx/migx.tutorials/utm-tags-for-modx/index.md: 55: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8370391Z ru/extras/migx/migx.tutorials/utm-tags-for-modx/index.md: 61: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8370844Z ru/extras/migx/migx.tutorials/utm-tags-for-modx/index.md: 64: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8371237Z ru/extras/migx/migx.tutorials/utm-tags-for-modx/index.md: 69: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8371607Z ru/extras/migx/migx.tutorials/utm-tags-for-modx/index.md: 77: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8376960Z ru/extras/migx/migx.tutorials/utm-tags-for-modx/index.md: 80: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8377484Z ru/getting-started/directory-structure.md: 148: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8377878Z ru/getting-started/friendly-urls/lighttpd.md: 16: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8378272Z ru/getting-started/installation/cli/config.xml.md: 60: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
- [x] 2019-12-06T14:34:53.8378638Z ru/getting-started/installation/cli/config.xml.md: 66: MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]

**Comment by Ibochkarev** [comment]
https://github.com/modxorg/Docs/commit/d6d2d4da368c07ba01388dd05d827c0369d31e31
https://github.com/modxorg/Docs/commit/4e17dd182bb28289192e9e0642206960471dbacd
https://github.com/modxorg/Docs/commit/48d157bab5944ee307761d700089034e6c4e412c
https://github.com/modxorg/Docs/commit/31b09bcec4cac369a0fc6be2e9988f68fd029419

**Comment by Ibochkarev** [comment]
@Mark-H markdown syntax - **Complete job**

**Comment by Mark-H** [comment]
You're awesome, @Ibochkarev! Thanks!
