### ISSUE TITLE
issue in component Breadcrumbs data-vocabulary.org schema deprecated

### ISSUE THREAD

**Issue by gravinos** [modxorg/Docs#163]
To solve Google Search Console error, I used this schema https://schema.org/BreadcrumbList

Modify file core/components/breadcrumbs/model/breadcrumbs/breadcrumbs.class.php

replace lines 149 to 161 width this code

`'bcTplCrumbCurrent' => '<li itemscope class="B_currentCrumb" itemtype="http://schema.org/BreadcrumbList">[[+text]]</li>',
            'bcTplCrumbCurrentLink' => '<a class="B_currentCrumb" itemprop="item" rel="[[+description]]" href="[[~[[+resource]]]]"><span itemprop="name">[[+text]]</span></a>',
            'bcTplCrumbFirst' => '<li class="B_firstCrumb" itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem">[[+text]]</li>',
            'bcTplCrumbHome' => '<a class="B_homeCrumb" itemprop="item" rel="[[+description]]" href="[[~[[++site_start]]]]"><span itemprop="name">[[+text]]</span></a>',
            'bcTplCrumbLast' => '<li class="B_lastCrumb" itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem">[[+text]]</li>',
            'bcTplCrumbMax' => '<li class="B_hideCrumb" itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem">[[+text]]</li>',
            'bcTplCrumbLink' => '<a class="B_crumb" itemprop="item" rel="[[+description]]" href="[[~[[+resource]]]]"><span itemprop="name">[[+text]]</span></a>',
            'bcTplCrumbOuter' => '<ul class="B_crumbBox" itemtype="http://schema.org/BreadcrumbList">[[+text]]</ul>',
            'bcTplCrumb' => '<li class="B_crumb" itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem">[[+text]]</li>',`

**Comment by Mark-H** [comment]
Sorry but I'm confused - are you suggesting a bug in the "breadcrumbs" package, suggesting a documentation change, or reporting an issue against the docs site itself?

**Comment by gravinos** [comment]
> Sorry but I'm confused - are you suggesting a bug in the "breadcrumbs" package, suggesting a documentation change, or reporting an issue against the docs site itself?

Hello Mark, 
since last week Google Search Console has been reporting on errors in the Breadcrumb "data-vocabulary.org schema deprecated", you can find more information here https://webmasters.googleblog.com/2020/01/data-vocabulary.html

![Schermata 2020-01-27 alle 16 25 22](https://user-images.githubusercontent.com/5929863/73187593-edf1e280-4121-11ea-85b1-b6f68154b9f7.png)
![Schermata 2020-01-27 alle 16 24 32](https://user-images.githubusercontent.com/5929863/73187594-edf1e280-4121-11ea-989d-e734def430bb.png)

**Comment by Mark-H** [comment]
Are you suggesting a bug in the "breadcrumbs" package, suggesting a documentation change, or reporting an issue against the docs site itself?

**Comment by gravinos** [comment]
> Are you suggesting a bug in the "breadcrumbs" package, suggesting a documentation change, or reporting an issue against the docs site itself?

I am suggesting to fix the component code because now using a deprecated markup! Simply!

**Comment by Mark-H** [comment]
This is the wrong place to do that. 

This repository is for the documentation.

**Comment by gravinos** [comment]
Sorry Mark, I was convinced to stay in the component page https://github.com/splittingred/Breadcrumbs, a link from the docs brought me in this page.

**Comment by JoshuaLuckers** [comment]
@gravino81 would it be possible to report an issue in my repo? https://github.com/JoshuaLuckers/BreadCrumb/issues

**Comment by gravinos** [comment]
> @gravino81 would it be possible to report an issue in my repo? https://github.com/JoshuaLuckers/BreadCrumb/issues

Hello Joshua, the problems were related to the BreadcrumbS component, however, I abandoned that component to use yours which is much better!
