### ISSUE TITLE
No images displayed on extending-modx/tutorials/developing-an-extra

### ISSUE THREAD

**Issue by Ibochkarev** [modxorg/Docs#175]
## Affected page(s)

https://docs.modx.com/3.x/en/extending-modx/tutorials/developing-an-extra/part-2

Failed to load resource: the server responded with a status of 404:

- 1-namespace-menu.png: Failed to load resource: the server responded with a status of 404 ()
- 4-creating-menu.png: Failed to load resource: the server responded with a status of 404 ()
- 3-menu-screen.png: Failed to load resource: the server responded with a status of 404 ()
- 16.png: Failed to load resource: the server responded with a status of 404 ()
- 26.png: Failed to load resource: the server responded with a status of 404 ()
- d1.png: Failed to load resource: the server responded with a status of 404 ()
- d2.png: Failed to load resource: the server responded with a status of 404 ()
- 18.png: Failed to load resource: the server responded with a status of 404 ()
- d3.png: Failed to load resource: the server responded with a status of 404 ()
- part-2: Unchecked runtime.lastError: The message port closed before a response was received.

https://docs.modx.com/3.x/en/extending-modx/tutorials/developing-an-extra

Failed to load resource: the server responded with a status of 404:

- https://docs.modx.com/download/attachments/33587481/doodleoutput1.png - 404
- https://docs.modx.com/download/attachments/33587481/doodles-maps.png - 404
- https://docs.modx.com/download/attachments/7be5a431a826c4c2097f6e6bdd67b307/doodles-dir-structure.png - 404

https://docs.modx.com/3.x/en/extending-modx/tutorials/developing-an-extra/part-3

Failed to load resource: the server responded with a status of 404:

- https://docs.modx.com/download/attachments/33947702/doodles-build-dir1.png - 404
- https://docs.modx.com/download/attachments/33947702/doodles-zip1.png 404

**Comment by ant-tar** [comment]
@Mark-H @Ibochkarev  do you have any idea where to look for these images (/download/attachements)? in old dumps maybe? I only have a google cache that comes to mind, but I'm not sure if there was something there :)  It seems there are no images at all for other doc pages(or please show me an example where it works, I will be glad to make a mistake ) ((

**Comment by Mark-H** [comment]
Here's what I've got from the old site: https://github.com/Mark-H/DocsImages

**Comment by ant-tar** [comment]
@Mark-H great, they are exist! Not sure how should I add them to Docs.modx.com, via commit or better move them manually?

**Comment by ant-tar** [comment]
https://docs.modx.com/download/attachments/33947702/doodles-build-dir1.png - 404
    https://docs.modx.com/download/attachments/33947702/doodles-zip1.png 404

f.e. here these images are: https://github.com/Mark-H/DocsImages/tree/master/attachments/33947702

**Comment by Mark-H** [comment]
I'm not sure why they're missing from the docs if they're in that repo..  I believe the conversion _should_ have copied images into the same directory as the documentation them but that must not have worked as expected. 

Putting all those files in doesn't sound like a good idea but perhaps there's a way to scrape the site for broken images and only add back what is still being referred to?

404s do list a bunch of images: https://docs.modx.com/stats/page-not-found

**Comment by ant-tar** [comment]
> Putting all those files in doesn't sound like a good idea but perhaps there's a way to scrape the site for broken images and only add back what is still being referred to?

to get rid of all unnecessary images and leave only those that are really needed we can f.e. do the following, please look here: 
https://github.com/modxorg/Docs/tree/2.x/ru/building-sites/tutorials

All the images needed for this Tutorials article are stored inside ... returning to  current issue, I could get the necessary images from this repo https://github.com/Mark-H/DocsImages and put them inside to https://docs.modx.com/3.x/en/extending-modx/tutorials/developing-an-extra/ etc., update image src's. So over time we will get everything we need ... and the other garbage will go into oblivion))

P.S. in order not to litter Docs repo with long list of files(a bit difficult to navigate as for me), maybe it will be good and come to the following convention - store images in some subdirectory, say, /img/ or /images/ 

![2021-03-05 17 56 06](https://user-images.githubusercontent.com/2815640/110132931-be111600-7ddc-11eb-905b-e941b03de07a.png)


Does it make sense?

Here is example: https://github.com/himurovich/Docs/blob/2.x/en/extending-modx/tutorials/developing-an-extra/part-3.md
I've added two necessary images under /img/ (en/extending-modx/tutorials/developing-an-extra/img)folder, it works.

**Comment by ant-tar** [comment]
so far fixed it in the way described above. I will be glad to further discussion, it looks like this problem will make itself felt more than once.
