### ISSUE TITLE
Not displayed on the site https://docs.modx.com/3.x/en/extending-modx/tutorials/

### ISSUE THREAD

**Issue by Ibochkarev** [modxorg/Docs#176]
## Affected page(s)

https://docs.modx.com/3.x/en/extending-modx/tutorials/

## What needs to be improved?

Not displayed on the site as there is no index.md in folder

## Relevant context

3x

**Comment by ant-tar** [comment]
it turned out that there are no Russian translations for inner pages, this will be the next

**Comment by Mark-H** [comment]
Fixed in 2.x, fix in 3.x will come with the next 2.x -> 3.x merge.
