### ISSUE TITLE
Issue on extending-modx/plugins/system-events

### ISSUE THREAD

**Issue by ant-tar** [modxorg/Docs#178]
## Affected page(s)

system events page

![2020-02-03+01 20 15](https://user-images.githubusercontent.com/2815640/73616377-89ec8400-4623-11ea-81e6-7c6324afd615.png)

## What needs to be improved?

Why do we need two identical menus? left one has wrong links but right is oK.
How can I remove that on the left? it seems I have no abilities for that via github.

**Comment by Mark-H** [comment]
Left one should be removed. That should be in the content of the file, while the one on the right is created automatically.

**Comment by Ibochkarev** [comment]
@himurovich @Mark-H 
https://docs.modx.com/current/en/extending-modx/plugins/system-events - This is not true - maybe the cache

![image](https://user-images.githubusercontent.com/2138260/73639578-df15ad80-4696-11ea-8664-3a97b39e8b39.png)

**Comment by ant-tar** [comment]
@Ibochkarev exaclty! I didn't know there was some kind of cache)) But when I tried edit the page I also couldn't see this left menu. Weird.
Anyway thanks!

**Comment by ant-tar** [comment]
> @himurovich @Mark-H
https://docs.modx.com/current/en/extending-modx/plugins/system-events - This is not true - maybe the cache

Please compare with https://docs.modx.org/3.x/en/extending-modx/plugins/system-events
What is wrong here?

**Comment by ant-tar** [comment]
@Ibochkarev @Mark-H 
See image please: 
![2020-02-03 12 43 01](https://user-images.githubusercontent.com/2815640/73642646-1e3a0380-4683-11ea-88c5-6e183e17db17.png)

Doubles. Not so good from SEO point of view, isn't it? 
Or is it part of the Plan? :)

**Comment by Mark-H** [comment]
One is specific to MODX 2. The other for MODX 3. They're separate pages that might be very different because of the changes in 3.

It is a little weird that you can't differentiate between them in the search results though. Perhaps we should add information into the header? Or change the name of the "Home" breadcrumb item to be "MODX 2.x" or "MODX 3.x"?

**Comment by ant-tar** [comment]
> One is specific to MODX 2. The other for MODX 3. They're separate pages that might be very different because of the changes in 3.

Yeah, already caught that idea
But at the first glance it’s not clear for the end user where to click.

> It is a little weird that you can't differentiate between them in the search results though. Perhaps we should add information into the header? Or change the name of the "Home" breadcrumb item to be "MODX 2.x" or "MODX 3.x"?

Agree, this is good idea to work with titles(f.e. for title postix "MODX x.x Documentation" instead "MODX Documentation") and Meta(MODX 2.x Home and MODX 3.x Home). 

I think there may be several differences. it should not be worse.  And away from Google penalty because of obvious doubles.

**Comment by Ibochkarev** [comment]
The problem is no longer observed
