### ISSUE TITLE
Issue on building-sites/settings

### ISSUE THREAD

**Issue by Craigeniah** [modxorg/Docs#186]
## Affected page(s)

https://docs.modx.com/current/en/building-sites/settings 

## What needs to be improved?

Missing/Broken image under the text:

> Creating new System Settings (via the GUI)
> 
> To create a new system setting, click the "Create New Settings" link under System -> System Settings

<img src="/2.x/en/building-sites/settings/system+settings+annotated.png" alt="">

Also missing alt tag while I'm looking at this.

## Relevant context

Seems like for all languages.

**Comment by Ibochkarev** [comment]
Fixed https://github.com/modxorg/Docs/commit/250bf3e89bd9dd24e9e5c7f69c4547ee4ef1cf1b
