### ISSUE TITLE
Issue on extending-modx/xpdo/class-reference/xpdo/xpdo.addpackage

### ISSUE THREAD

**Issue by ant-tar** [modxorg/Docs#187]
Hi,
What is wrong with translation block for this page(and other XPDO siblings too - these ones: https://take.ms/fSeyo)? It say there are no translations. At the same time we have appropriate EN and RU pages for XPDO.Addpackage method:
https://docs.modx.com/current/en/extending-modx/xpdo/class-reference/xpdo/xpdo.addpackage
https://docs.modx.com/current/ru/extending-modx/xpdo/class-reference/xpdo/xpdo.addpackage

![2020-02-17+23 49 20](https://user-images.githubusercontent.com/2815640/74685765-825eda80-51e0-11ea-898e-ed8b188ea88c.png)

**Comment by Mark-H** [comment]
Hm. I'm not seeing why that's not showing up. Could be a bug, will need to investigate it further.

**Comment by Mark-H** [comment]
Probably due to missing index page also discussed in #191

**Comment by ant-tar** [comment]
discussed as well here: https://github.com/modxorg/Docs/issues/262
I believe the issue may be closed.
