### ISSUE TITLE
Issue on extending-modx/xpdo/class-reference/xpdo/xpdo.addpackage- we need crumbs menu!

### ISSUE THREAD

**Issue by ant-tar** [modxorg/Docs#191]
## Affected page(s)

This page and all other "children" pages

## What needs to be improved?

I believe we need crumbs menu at the top of page. See screenshot: 

![2020-02-19 01 13 05](https://user-images.githubusercontent.com/2815640/74782958-9a545e00-52b5-11ea-8722-44c3b0b64c8a.png)

When I'm on the page I'm trying to understand where I'm now and how to move f.e. to upper pages...but where exactly? Honestly I know that addPackage is somewhere under xPDO but you agree this isn't so obvious for other visitors. Crumbs will help here. F.e. compare with other "category" page:

https://docs.modx.com/current/en/extending-modx/xpdo/class-reference

![2020-02-19 01 20 24](https://user-images.githubusercontent.com/2815640/74783147-1cdd1d80-52b6-11ea-971e-df35d484f322.png)

I know where my location here.

**Comment by Mark-H** [comment]
One of the parents (class reference?) seems to lack an index page, that's probably why. Might also explain the translation not linking up if it doesn't appear in the menu map.

**Comment by Mark-H** [comment]
Crumbs menu is back https://docs.modx.com/current/en/extending-modx/xpdo/class-reference/xpdo/xpdo.addpackage
