### ISSUE TITLE
Issue on extending-modx/plugins/system-events/onpluginsave

### ISSUE THREAD

**Issue by maxzhurkin** [modxorg/Docs#192]
## Affected page(s)
https://docs.modx.com/current/en/extending-modx/plugins/system-events/onpluginsave

## What needs to be improved?
Same description as OnPluginRemove
Needs correct description

## Relevant context
Affected at least English and Russian versions

**Comment by Ibochkarev** [comment]
Fixed. @maxzhurkin Thanks
