### ISSUE TITLE
Request to document the system event "OnBeforeRegisterClientScripts"

### ISSUE THREAD

**Issue by JoshuaLuckers** [modxorg/Docs#202]
## Request for new documentation

Extending MODX -> Writing Plugins -> System Events is missing document for the event "OnBeforeRegisterClientScripts".

## Relevant sources

[Link to the source code](https://github.com/modxcms/revolution/blob/c3aa911013469ba4b151744b8e69064e55111e5e/core/model/modx/modresponse.class.php#L66)

**Comment by Ibochkarev** [comment]
@Jako please help

**Comment by JoshuaLuckers** [comment]
More info about this event can be found in the PR introducing it: https://github.com/modxcms/revolution/pull/14123

**Comment by Ibochkarev** [comment]
@sergant210 please help

**Comment by Jako** [comment]
Done.

**Comment by Ibochkarev** [comment]
Added #212 
@Jako Thanks
