### ISSUE TITLE
Issue on building-sites/tag-syntax/output-filters

### ISSUE THREAD

**Issue by Serifenlos** [modxorg/Docs#209]
https://docs.modx.com/current/en/building-sites/tag-syntax/output-filters

in the example of "notempty…" are tow brackets too much
```[[[[+name:notempty=`Hello `[[+name]]`!`]]```

must be
```[[+name:notempty=`Hello `[[+name]]`!`]]```

**Comment by Ibochkarev** [comment]
@Serifenlos Thanks
