### ISSUE TITLE
Automatically convert links to point to right URLs

### ISSUE THREAD

**Issue by Mark-H** [modxorg/Docs#21]
Both due to the major reshuffling of content and simply the conversion from the old site, there are tons of incorrect links in the content.

Most of those still work -  because of the redirects that are in place. 

But ideally, a mass automated link update should be executed that fetches the markdown files to look at URLs in the content, see if there's a known redirect (or perhaps other transformation) that should be applied to it, and writes the file with the correct URL. 

One example for that is the links under "See also" at http://modxdocs.mhserver.nl/current/en/building-sites/client-proofing/dashboards/usergroups - those links point to an incorrect URL, and redirect to the right one.

While this process runs, it could also create a list of potentially broken links that should be manually checked. I'd expect a broken link to be a link that is not external (starts with http(s)://), or anchors, and also do not exist in the doc_sources dir as markdown.

**Comment by Mark-H** [comment]
498386ffeed32a34428f883b896a54d9165a885e @ Mark-H/DocsApp doesn't rewrite the content, but it does prevent the extra redirect by parsing broken links during rendering and checking for the redirect early.

**Comment by Mark-H** [comment]
@Ibochkarev fixed a lot of links in #24 - would still be good to add some automated scanning that checks every link in every file, autofixes what it can based on the redirects, and reports what can't be automatically fixed.

**Comment by Ibochkarev** [comment]
@Mark-H Can be closed. I fixed it.
