### ISSUE TITLE
Issue on getting-started/what-is-modx

### ISSUE THREAD

**Issue by vietnetz-workplace** [modxorg/Docs#211]
## Affected page(s)

Please provide a link to the page(s) that have an issue, or even better, the link to the source file in the repository. For long pages, please include approximately where the problem is (heading or line numbers)

## What needs to be improved?

Be as specific as possible; is there a typo, incorrect capitalisation of MODX, or does an entire section need work? What is unclear or incorrect? If an inaccuracy or unclear description was discussed on the forums or slack, include a link to that discussion.

## Relevant context

Is the problem only in a specific version or language? Then please include that.

**Comment by Mark-H** [comment]
Can you please explain the problem you were having with this page? ;)
