### ISSUE TITLE
Missing undocumented core events

### ISSUE THREAD

**Issue by Jako** [modxorg/Docs#214]
## Request for new documentation

A lot of not documented core events exist like 

- [x] - OnResourceAutoPublish
- [x] - OnResourceDelete
- [x] - OnResourceUndelete
- [x] - OnResourceBeforeSort
- [x] - OnResourceSort
- [x] - OnResourceDuplicate

## Relevant sources

See _build/data/transport.core.events.php for available core events.

**Comment by Ibochkarev** [comment]
@Jako https://github.com/modxorg/Docs/commit/35809ed92ffc5cea8e21a39cd6c9f8621422a186

**Comment by Ibochkarev** [comment]
https://bobsguides.com/modx-revolution-events.html
