### ISSUE TITLE
Issue on extras/formit/formit.tutorials-and-examples/examples.simple-contact-page

### ISSUE THREAD

**Issue by Malaysiatic** [modxorg/Docs#219]
## Affected page(s)
This is an ambiguous page that does not provide clear information:
What is the suggested snippet to be called?
If I copy the example snippet code and create a snippet with it I have no idea what to save it as because there is no instructions.
Link to page:
https://docs.modx.org/current/en/extras/formit/formit.tutorials-and-examples/examples.simple-contact-page#snippet-tag

**Comment by jaygilmore** [comment]
When we refer to "call it" in the documentation, we mean to call a reference to it, similar to a PHP function. In this case, we're not referring to the use of call it as in giving it a name. I.e., we call a Snippet in our Resource. 

I think you're misunderstanding how Extras work in MODX, @Malaysiatic. In order to use any of the Extras listed in the documentation, you first need to install them using Extras>Installer in MODX Revolution, and then once you've installed FormIt, you can call it (make reference to the installed Snippet) in your Resource, Chunk or Template. So, to implement the example, you first install FormIt from the Installer and then you call (reference to it) in the Resource with the Snippet call code provided.

**Comment by Malaysiatic** [comment]
Hi jaygilmore,

Thanks for taking the time to reply :-)

Actually I did have Formit installed. My confusion was with the instructions, or rather lack of them. It is an examples page but it did not give any instruction on 'where' to place the code. This is left to complete guesswork for the bewildered reader who is eager to learn. 
Fortunately I found the answer on another page, the snippet actually goes in the same place as the form code. 
I find it really bizarre that coding samples are freely given without instructions of where to place them, yet this information is readily available on another page. 
Very strange indeed.

**Comment by jaygilmore** [comment]
I guess the example assumes you've read the introduction page to FormIt which explains how to use it which is here: https://docs.modx.org/current/en/extras/formit under the section "How to Use". 

Are you suggesting we revisit the basic instructions with the example? 

That said, It may make sense for someone to expand on the instructions or at least refer them to the "How to Use" section before getting started.

**Comment by Malaysiatic** [comment]
_"Are you suggesting we revisit the basic instructions with the example?"_

Yes.
I am not saying I am right for not not reading the "how to use it" page first, but, people are hardwired to jump to the "examples" page because time is so precious that people like me tend to try to read the essential and get frustrated when comparing MODX examples & instructions to similar pages outside of MODX.

I was just a bit miffed when I wrote the initial post, but yes, I do think MODX could and should do better with their instructions and examples pages, not just Formit but all of their documentation. 
There seems too much emphasis on creating a platform for seasoned coders to use, this is a pity because it is a fantastic CMS.
It just makes things more challenging for someone like me who just wants to publish stuff but still develop my website on a shoestring.
I'm not a coder but I like to learn, without clear instructions this steepens my curve.

**Comment by jaygilmore** [comment]
@Malaysiatic thanks for your feedback. You bring up some entirely valid points about the documentation. It would be good to make it an aspect of each documentation page: to help the user solve their problem/get going as quickly as possible with what's in front of them without having to hunt for more information. We hope to be able to make some progress on improving the docs this year. It's not easy work and it is quite time consuming. Most efforts generally focus on improving the CMS and Extras when time permits. But documentation is the gateway to adoption and making for more people who can contribute tot he docs.

**Comment by Mark-H** [comment]
To summarise, this issue would be resolved if the linked page explains where what sample code goes.

**Comment by ant-tar** [comment]
if you don't mind  working on updating this documentation today

**Comment by Mark-H** [comment]
Should be easier to follow for new users now - thanks @himurovich  :)
