### ISSUE TITLE
Include images in repository

### ISSUE THREAD

**Issue by Mark-H** [modxorg/Docs#22]
I have a bunch of images locally (which I uploaded to the server with the first deployment), but those should become part of the repository. I'm thinking an `images` directory in each language directory, so they can be localised as needed. 

Ideally the images should not named in the current random-file-hash way, but actually useful so the context is enough to be able of going through and updating them... which would require some content modifications.

**Comment by Ruslan-Aleev** [comment]
It also makes sense to update the images to the images of the current version of MODX.
Because even between MODX 2.x and 3.x there are big differences, not to mention the old versions.

**Comment by JoshuaLuckers** [comment]
Is it also possible to add a (fig)caption to the images?
