### ISSUE TITLE
Issue on building-sites/tag-syntax/output-filters/index

### ISSUE THREAD

**Issue by avanturist888** [modxorg/Docs#225]
## Affected page(s)

https://docs.modx.com/current/en/building-sites/tag-syntax/output-filters/index

## What needs to be improved?

Bug with modx tags: 
![image](https://user-images.githubusercontent.com/801823/91837819-355ec500-ec55-11ea-9719-ef89397b07a9.png)

**Comment by Ibochkarev** [comment]
Thanks. Fixed
