### ISSUE TITLE
Broken image links on extras/wayfinder/wayfinder-introductory-examples

### ISSUE THREAD

**Issue by beuckbj** [modxorg/Docs#227]
## Affected page(s)

https://docs.modx.com/current/en/extras/wayfinder/wayfinder-introductory-examples#before-you-start
## What needs to be improved?

The included images can't found by the browser. On the developer console I see only a 404 error. Sample image is:
https://docs.modx.com/2.x/en/extras/wayfinder/wf+regions.png

**Comment by Ibochkarev** [comment]
@beuckbj Thanks
