### ISSUE TITLE
Issue on extras/simplesearch/simplesearch/faceted-search-through-posthooks

### ISSUE THREAD

**Issue by superspace** [modxorg/Docs#231]
## Affected page(s)

Code examples on https://docs.modx.com/current/en/extras/simplesearch/simplesearch/faceted-search-through-posthooks

## What needs to be improved?

In example code placeholders are prefixed with 'sisea', but this is outdated. Current default prefix is 'simplesearch'

**Comment by Ibochkarev** [comment]
@superspace Thanks
