### ISSUE TITLE
Issue on extras/simplesearch/index

### ISSUE THREAD

**Issue by svenhabex** [modxorg/Docs#235]
## Affected page(s)

- simplesearch/model/simplesearch/driver/simplesearchdriver.class.php
- simplesearch/model/simplesearch/driver/simplesearchdriverbasic.class.php

## What needs to be improved?

Combination of parameters "contexts" and "ids" does not work as expected. I want to search all the child resources of a specified parent in the given context. But only the child resources of the current context are searched.

## Relevant context

Example:
       [[!SimpleSearch? 
          &tpl=`search-resultsTpl`
          &containerTpl=`search-containerTpl`
          &pagingSeparator=``
          &searchIndex=`s`
          &docFields=`pagetitle,content`
          &highlightTag=`strong` 
          &perPage=`10`
          &urlScheme=`abs`
          &ids=`11`
          &contexts=`web`
        ]]

If I look in the code it appears that there is never a context specified in getChildIds() function on line 172 of simplesearchdriver.class.php. It will be solved if the context specified in &contexts is set here.

**Comment by Mark-H** [comment]
Is this a documentation error or a bug in SimpleSearch?

**Comment by svenhabex** [comment]
A bug in simplesearch

**Comment by Ibochkarev** [comment]
@svenhabex Please open the issue in the add-on repository https://github.com/modxcms/SimpleSearch/issues
