### ISSUE TITLE
Issue on extras/migx/migx.tutorials

### ISSUE THREAD

**Issue by ghost** [modxorg/Docs#240]
## Affected page(s)

https://docs.modx.com/current/en/extras/migx/migx.tutorials
## What needs to be improved?

Links are broken

## Relevant context

<img width="712" alt="Screen Shot 2020-12-15 at 11 54 02" src="https://user-images.githubusercontent.com/1073780/102199440-5083d680-3ecc-11eb-842a-32b42d8c0312.png">

**Comment by Ibochkarev** [comment]
@sottwell Thanks. Fixed
