### ISSUE TITLE
Issue on getting-started/installation/git

### ISSUE THREAD

**Issue by Ibochkarev** [modxorg/Docs#259]
## Affected page(s)

https://docs.modx.com/3.x/en/getting-started/installation/git

## What needs to be improved?

No installation information with composer

## Relevant context

3.x

**Comment by ghost** [comment]
Do you mean this part of the page? https://docs.modx.com/3.x/en/getting-started/installation/git#git-install-for-3-x-development

**Comment by Mark-H** [comment]
That page should definitely be mildly rewritten for the changes in 3.x. The composer install is not an optional step but very much required...

**Comment by opengeek** [comment]
> Do you mean this part of the page? https://docs.modx.com/3.x/en/getting-started/installation/git#git-install-for-3-x-development

While that part is valid, the previous section is missing any mention of running `composer install` which is required in order to complete the installation process when pulling it directly from git.

**Comment by Ibochkarev** [comment]
https://modx3.org/try-modx3

**Comment by ghost** [comment]
According to the composer docs, it's all done with create-project:
```
You can use Composer to create new projects from an existing package. This is the equivalent of doing a git clone/svn checkout followed by a composer install of the vendors.
```

**Comment by opengeek** [comment]
> According to the composer docs, it's all done with create-project:
> 
> ```
> You can use Composer to create new projects from an existing package. This is the equivalent of doing a git clone/svn checkout followed by a composer install of the vendors.
> ```

I don't use create-project for a variety of reasons. As I said, it is a valid approach, but that is not the only way to do it and it does not help if you are forking the project and contributing as you would generally want to clone your fork or use the GitHub CLI tool to clone your fork.

**Comment by Mark-H** [comment]
#267 added small note of this in another place, but still worth making much more obvious it's needed.
