### ISSUE TITLE
getting-started/maintenance missing from menu; needs an index file

### ISSUE THREAD

**Issue by Mark-H** [modxorg/Docs#26]
## Affected page(s)

https://github.com/Mark-H/Docs/tree/2.x/en/getting-started/maintenance

## What needs to be improved?

Should be part of the generated menu, which currently requires an index.md in the root of that directory, or a `maintenance.md` file one dir up. 

## Relevant versions

The problem affects the following version(s): 

- [x] 2.x (current)
- [x] 3.x

**Comment by achterbahn** [comment]
PR #36
