### ISSUE TITLE
Issue on building-sites/tutorials/creating-a-blog

### ISSUE THREAD

**Issue by SwapnilAkolkar** [modxorg/Docs#270]
## Affected page(s)

https://docs.modx.com/current/en/building-sites/tutorials/creating-a-blog

## What needs to be improved?
I not found how you connected the blog categories to blog post no any link connection at all!! in this article.

## Relevant context

not sure.

**Comment by SwapnilAkolkar** [comment]
Also I not get the blog home page even I set the `[[!getResourcesTag?
  &elementClass=`modSnippet`
  &element=`getResources`
  &tpl=`blogPost`
  &parents=`34,35`
  &limit=`5`
  &includeContent=`1`
  &includeTVs=`1`
  &showHidden=`0`
  &hideContainers=`1`
  &cache=`0`
  &pageVarKey=`page`
]]
[[!+page.nav:notempty=`
<nav class="paging" role="Blog">
  <ul class="pageList">
    [[!+page.nav]]
  </ul>
</nav>
`]]
`
code also changed id 34 and 35 with  the blog category  resources id of mine ids.

**Comment by Mark-H** [comment]
Please note this repository is for reporting specific issues with the documentation. Please use the forum to get assistance: https://community.modx.com/

**Comment by SwapnilAkolkar** [comment]
ok thanks

**Comment by SwapnilAkolkar** [comment]
But I still think its bug in documentation if you read the specific article it discuss about categories of blog at initial stage but its not implemented till end. cause I read something personal and technical categories. But its ok cause I new to this cms. I may be wrong.
