### ISSUE TITLE
Keep the translated documentation manageable 

### ISSUE THREAD

**Issue by JoshuaLuckers** [modxorg/Docs#29]
## Affected page(s)

All translated documentation pages.

## What needs to be improved?

Directories and files for translated documentation should mirror the English content. This makes it easier to manage:
- Only the language key has to be changed which makes switching languages easier.
- It's easier to find pages that are not yet translated.
- etc.

**Comment by Mark-H** [comment]
That's what the `translation` key is for. While it can be simpler to keep the same url structure, I'd much rather have the Dutch docs use Dutch words in the url.

**Comment by JoshuaLuckers** [comment]
How are we able to find all related translation files for a certain page without using external tooling?
Maybe you can define an alias for the URL in the .md file instead of the translation key?

Using the translation key i.m.o conflicts with:
> The beauty of markdown is that it is independent from specific technologies or tools`

**Comment by JoshuaLuckers** [comment]
Mirroring the directory and files of the "main" language is also common practice in other documentation projects (and even in MODX for lexicons). 

However if you want to keep the translated file names maybe it's good to have some kind of reference file where you have a table listing the translated versions of files?
