### ISSUE TITLE
/building-sites/settings incomplete list

### ISSUE THREAD

**Issue by ant-tar** [modxorg/Docs#293]
## Affected page(s)

https://docs.modx.com/current/en/building-sites/settings

## What needs to be improved?

I noticed that the list of system variables is out of date(there are no log_deprecated, default_media_source, default_username, etc.), we have 177 items VS ~250 settings for a typical 2.8.1 instance.
I'm working with that now, I would be very grateful if someone has any kind of settings list that have appeared in recent releases (pairs like "parameter" - "release #"). 
Now I use Google and MODX changelog analysis. :)

## Relevant context

I'm going to update 2.x. only, please port everything you need to 3.x DOCS after PR.

**Comment by Mark-H** [comment]
Looking at the history here may help: https://github.com/modxcms/revolution/commits/2.x/_build/data/transport.core.system_settings.php

Dates, often a link to a PR which may have additional info on what it does, etc :) 

Thanks for your hard work! ❤️

**Comment by ant-tar** [comment]
> Looking at the history here may help: https://github.com/modxcms/revolution/commits/2.x/_build/data/transport.core.system_settings.php

I have to guess, useful link, it will help me a lot. Thank you Mark!

**Comment by ant-tar** [comment]
@Mark-H @Ibochkarev  all 255 EN system settings are up to date, only RU translations will be needed. 
If you don't mind you can send them already to Docs. https://github.com/modxorg/Docs/pull/295

**Comment by Ibochkarev** [comment]
@himurovich Thanks
