### ISSUE TITLE
Formit extra is absent in left tree menu

### ISSUE THREAD

**Issue by ant-tar** [modxorg/Docs#304]
## Page not found

https://docs.modx.com/current/ru/extras/formit

The page exists but absent in the left menu.

![2021-03-24 15 15 57](https://user-images.githubusercontent.com/2815640/112436829-3f622580-8d57-11eb-9dc4-a73ca3ed325b.png)

More details regarding page update: https://github.com/modxorg/Docs/pull/303

**Comment by ant-tar** [comment]
Hi guys, @Mark-H @Ibochkarev !
I've added more extra translations, left menu has the same look as before, I don't see Formit and these new ones ((
Can I help you here? If so let me know please, I'll try to figure this out, what is wrong here, some kind of index issues?

**Comment by ant-tar** [comment]
Sorry to ping again and again, but users and I can't see newly translated extras, massively added system settings, any other new pages in the left menu .. it turns out that the results of all the last work are unfortunately not yet available. I'm happy to help fix this, just don't know how yet.

**Comment by Mark-H** [comment]
Ah the menu generation is just completely broken because of invalid frontmatter somewhere:

````
Regenerating navigation cache...
- 2.x/en
- 2.x/ru

In Parser.php line 485:
                                                                                                                                                            
  Unable to parse at line 3 (near "description" "Если включен этот параметр, то все амперсанды в ссылках будут заменены в соответствии с форматом XHTML"")  
  .                                                                                                                                                       
````
Any chance you can tell from that description what page the invalid frontmatter is in?

**Comment by Mark-H** [comment]
Found it, see: https://github.com/modxorg/Docs/commit/8d7eaf5bbeb7fbc6acbd491773be195b38740d38

Menu now generates again with all items ;)

**Comment by ant-tar** [comment]
it turns out it was my mistake .. sorry @Mark-H , and thanks for update!! Yep, it works finally!!!
