### ISSUE TITLE
Remove manual table of contents

### ISSUE THREAD

**Issue by Mark-H** [modxorg/Docs#31]
## Affected page(s)

A lot of pages.

## What needs to be improved?

Previously, table of contents were manually added into the content. We're now automatically generating them from headers, leading to duplicated table of contents. In many cases the manual table of contents is also marked as a broken link,  but that might be more of a bug in the app.

All manual table of contents should be removed from all pages. 

For example: https://docs.modx.org/current/en/getting-started/installation/advanced

## Relevant versions

The problem affects the following version(s): 

- [x] 2.x (current)
- [x] 3.x

**Comment by Ibochkarev** [comment]
@Mark-H Help in this matter need? Or do you write the script yourself?

**Comment by Mark-H** [comment]
I'm not entirely sure if it's possible to do this with a script. They're just list of links, and we don't want _all_ list of links gone

**Comment by Ibochkarev** [comment]
OK. I will do it today - tomorrow.

**Comment by Mark-H** [comment]
Fixed in #33
