### ISSUE TITLE
Issue on getting-started/friendly-urls

### ISSUE THREAD

**Issue by era404design** [modxorg/Docs#320]
## Affected page(s)

https://docs.modx.com/current/en/getting-started/friendly-urls

## What needs to be improved?

Just noticed a few typos:

**It the setting is set to "Yes" (the default), you will see a full path to the current page in the URLs.**

should read

**_If_ the setting is set to "Yes" (the default), you will see a full path to the current page in the URLs.**

and:

**If you have only one front-end context (e.g., 'web') you can usually leave out the exclamation point to speed of page loads:**

should read

**If you have only one front-end context (e.g., 'web') you can usually leave out the exclamation point to _improve the_ speed of page loads:**

and:

**Severs can be quite touchy about what's in an .htaccess file.**

should read

**_Servers_ can be quite touchy about what's in an .htaccess file.**

**Comment by ant-tar** [comment]
Thanks @era404design will address this asap!

**Comment by ant-tar** [comment]
@era404design page has been updated, please have a look: https://docs.modx.com/current/en/getting-started/friendly-urls
