### ISSUE TITLE
Issue on getting-started/maintenance/upgrading/2.8.2 - Migx & media sources

### ISSUE THREAD

**Issue by BigBlockStudios** [modxorg/Docs#333]
I have a migx config that creates directories in 2 specific media sources for a project manager tool within the modx manager.
The directories are no longer automatically created after the update to 2.8.2

The tools process is: 
- create and save a new project
- the code will then create the directories for that project in the media sources (not working)
- the media sources basepath and baseurl are defined as:

`[[!migxObjectMediaPath? &pathTpl=`assets/projects/{id}/documents/` &createFolder=`1`]]`

So here is the funny part ... all I have to do is view the Media->Media Sources page, I don't even have to open the specific media source ... and the directories will be created - the user can return to the project and start adding files.

Seems to be cache related so I am including the core/cache/media_sources/web/source.cache.php files (which looks very odd)
[source.cache.txt](https://github.com/modxorg/Docs/files/6435658/source.cache.txt)

**Comment by Mark-H** [comment]
This repository is for requesting documentation changes or improvements, to get help please post on the forum or to report an issue with MODX or MIGX please post an issue in their respective repositories instead.
