### ISSUE TITLE
Issue on extending-modx/parsing-tags

### ISSUE THREAD

**Issue by shedko** [modxorg/Docs#335]
## Affected page(s)
https://docs.modx.com/current/ru/extending-modx/core-model/modchunk/modchunk.getcontent

## What needs to be improved?

Добавить информацию про
https://docs.modx.com/current/ru/extending-modx/parsing-tags
Хотябы в "Смотрите также".

**Comment by Ibochkarev** [comment]
@himurovich добавь плиз

**Comment by ant-tar** [comment]
@Ibochkarev добавил https://github.com/modxorg/Docs/pull/336

**Comment by Ibochkarev** [comment]
Added #336 @himurovich @shedko Thanks
