### ISSUE TITLE
Integrating Templates: Working with templates, chunks,snippets, etc.

### ISSUE THREAD

**Issue by achterbahn** [modxorg/Docs#38]
## Affected page(s)

https://github.com/Mark-H/Docs/blob/2.x/en/building-sites/integrating-templates/index.md

## What needs to be improved?

Topics to be covered:
- building templates
- chunks,
- using snippets
- best practices, etc - (mayb) this should be in the form of a guide/tutorial)

## Relevant versions

The problem affects the following version(s): 

- [x] 2.x (current)
- [ ] 3.x

**Comment by Ibochkarev** [comment]
Fixed in #98
