### ISSUE TITLE
Issue on extras/flexibility

### ISSUE THREAD

**Issue by terrybarth** [modxorg/Docs#393]
The destination for this link appears to have been hijacked or infected.

Flexibility - version 3.0.6-rc http://flexibilitymodx.com

![screenshot-www flexibilitymodx com-2022 03 19-10_46_33](https://user-images.githubusercontent.com/526281/159128106-b0267fcd-3bf8-4d76-8258-bf727bea0e6d.png)
/

**Comment by Mark-H** [comment]
Removed the link.
