### ISSUE TITLE
Issue on extras/formit

### ISSUE THREAD

**Issue by bonanzza-web** [modxorg/Docs#406]
Не работает так как должен! При отправлении пустой формы не выходит сообщение об ошибке, вместо этого страница перегружается и скроллится вверх. Сайт bonanzza.ru изза неработоспособности формы не могу перенести верстку, думаю поставить wordpress, там хоть информации больше

**Comment by Ibochkarev** [comment]
@bonanzza-web доброго времени суток!

1) Это не репозиторий дополнения, а документация
2) Официальный репозиторий дополнения https://github.com/Sterc/FormIt
3) Вы бы хотя бы приложили код вызова дополнения
4) Можно написать и поискать решение на https://modx.pro/ или https://t.me/ru_modx
5) https://www.riwkus.ru/notes/web/back-end/modx/formit/ или https://web-revenue.ru/modx-revo/formit для примера 
6) Не разобравшись в малейшей проблеме менять CMS - честно сказать такое себе решение!
