### ISSUE TITLE
Issue on extending-modx/developing-restful-api

### ISSUE THREAD

**Issue by AntonFix** [modxorg/Docs#410]
It's not work for MODX Revolution 3.
Error 500.
`[2022-06-05 11:06:44] (ERROR @ /home/***/core/src/Revolution/Rest/modRestServiceRequest.php : 118) PHP warning: array_walk_recursive() expects parameter 2 to be a valid callback, class 'modRestServiceRequest' not found
`

**Comment by Ibochkarev** [comment]
Fixed https://github.com/modxcms/revolution/commit/ad4030b91e8a9638e1196466a391437557f5756c
