### ISSUE TITLE
Issue on extras/login/login.tutorials/basic-setup

### ISSUE THREAD

**Issue by CamilleBeaute** [modxorg/Docs#411]
## Affected page(s)

https://docs.modx.com/3.x/en/extras/login/login.tutorials/basic-setup

## What needs to be improved?

The directions are not valid for MODX 3.x. There is no way to create a Resource Group from the manager interface per the directions.

## Relevant context

Affects MODX 3.x

**Comment by Mark-H** [comment]
Should be fixed now. It's under Content, not Security.
