### ISSUE TITLE
Issue on extras/pdoTools/Parser

### ISSUE THREAD

**Issue by CamilleBeaute** [modxorg/Docs#413]
## Affected page(s)

https://docs.modx.com/3.x/en/extras/pdoTools/Parser

## What needs to be improved?

The makeurl syntax `{$_modx->makeUrl(number)}` does not work, however `{$modx->makeUrl(number)}` (without the '_' before 'modx') does.

**Comment by Ibochkarev** [comment]
@CamilleBeaute The documentation is correct!
You can use syntax  `{$_modx->makeUrl(number)}` or like `{number | url}`

To use the features of the template generator with a hair dryer, you must first enable it in the system settings!
