### ISSUE TITLE
Issue on extending-modx/tutorials/using-custom-database-tables

### ISSUE THREAD

**Issue by ghost** [modxorg/Docs#414]
[using custom database tables](https://docs.modx.com/3.x/en/extending-modx/tutorials/using-custom-database-tables#) 

Please provide a link to the page(s) that have an issue, or even better, the link to the source file in the repository. For long pages, please include approximately where the problem is (heading or line numbers)

## What needs to be improved?

I get an error when trying to add namespace , Modx is running in Xampp.
The path in modx to xpdo is supposed to be core/vendor/xpdo/src/xPDO/ ,but my path is core/vendor/xpdo/xpdo/src/xPDO/
xpdo is 2 directories?

This is on modx3.0.1

**Comment by kudykam** [comment]
I got error when running snippet [[!ToDo? &action=`generate`]]
`(ERROR @ C:\xampp\htdocs\core\cache\includes\elements\modx\revolution\modsnippet\45.include.cache.php : 9) PHP warning: Undefined array key "action"`

This is on modx3.0.1

**Comment by Mark-H** [comment]
This repository is not for getting help with MODX. Please use the forum for that.

If there's an issue in the documentation please clarify the issue with exactly what is wrong and how that should be fixed.
