### ISSUE TITLE
Issue on extras/migx/migx.tutorials/use-resource-specific-mediasource-and-multifile-uploader

### ISSUE THREAD

**Issue by dishly** [modxorg/Docs#429]
I needed to upload multiple files in Migx to create galleries. I followed this official Modx tutorial step by step:

https://docs.modx.com/3.x/en/extras/migx/migx.tutorials/use-resource-specific-mediasource-and-multifile-uploader

Everything works fine, the only issue is that now every time I click on any TV in the manager an empty directory is created (under “assets/resourceimages/”) named with exactly the same ID as the TV I clicked.

It looks like the snippet migxResourceMediaPath (from the Media Source “ResourceMediaPath”) gets executed every time I click on a Template, TV or Chunk in the “Elements” tab of the manager.

I changed &createFolder to 0 but its not an ideal solution if you wish to dynamically create a folder for each Migx gallery.

**Comment by Mark-H** [comment]
Is this an issue with the documentation or something you'll want to report to MIGX instead?

**Comment by dishly** [comment]
Yes, I think this issue is related to the migxResourceMediaPath snippet. I've reported the issue to MIGX. Thanks
