### ISSUE TITLE
Issue on extending-modx/xpdo/custom-models/defining-a-schema/database-and-tables

### ISSUE THREAD

**Issue by BobRay** [modxorg/Docs#443]
## Affected page(s)

[extending-modx/xpdo/custom-models/defining-a-schema/database-and-tables](extending-modx/xpdo/custom-models/defining-a-schema/database-and-tables)

## What needs to be improved?

Is the recommendation for MyISAM still good? I notice that the MODX 3 schema uses InnoDB.

**Comment by Mark-H** [comment]
Updated, thanks.
