### ISSUE TITLE
Issue on extending-modx/xpdo/class-reference/xpdogenerator/xpdogenerator.writeschema

### ISSUE THREAD

**Issue by BobRay** [modxorg/Docs#448]
## Affected page(s)

[https://docs.modx.com/current/en/extending-modx/xpdo/class-reference/xpdogenerator/xpdogenerator.writeschema](https://docs.modx.com/current/en/extending-modx/xpdo/class-reference/xpdogenerator/xpdogenerator.writeschema)

Please provide a link to the page(s) that have an issue, or even better, the link to the source file in the repository. For long pages, please include approximately where the problem is (heading or line numbers)

## What needs to be improved?

This seems to be a dead link (or the server is down)

**Comment by Mark-H** [comment]
Seems to work here. If you're still not getting to it successfully please reopen.

**Comment by BobRay** [comment]
Works for me now too.
