### ISSUE TITLE
[3.x] System Setting cache_disabled is still recommended

### ISSUE THREAD

**Issue by zahlenhexe** [modxorg/Docs#450]
## Affected page(s)

https://docs.modx.com/3.x/en/contribute/code/contributors-guide

## What needs to be improved?

https://github.com/modxorg/Docs/blob/1d22ecc4999a1c5e4dacc97cea0252a029f0968b/en/contribute/code/contributors-guide.md?plain=1#L194

## Relevant context

I don't know. But in 3.x it seems that this setting is removed. I think already since 2.7.0? 
https://github.com/modxcms/revolution/commit/29c21e67f0f43a39255cd9e7f0ef27fc43c378f8

**Comment by Mark-H** [comment]
Removed in #463, thank you.
