### ISSUE TITLE
extras/login/login.resetpassword

### ISSUE THREAD

**Issue by jacksonsophat** [modxorg/Docs#462]
I have this snippet [[!ResetPassword? &loginResourceId=`72`]] but after I clicked a reset password link. It does take me to the login page.
Not sure if anyone had this issue before?

Thank you.

**Comment by Mark-H** [comment]
Please use the MODX forum to get support. 

If through that an issue in the documentation is found, then open an issue here with specific information of what is wrong and what it should say instead.

**Comment by jacksonsophat** [comment]
Sorry about that. And thank you for your direction.
