### ISSUE TITLE
GIIN Career Center Formatting Issue

### ISSUE THREAD

**Issue by nkokimura** [modxorg/Docs#476]
## Affected page(s)

https://jobs.thegiin.org/job/6578/mission-related-investments-programme-coordinator/

## What needs to be improved?

I noticed that commas in lines starting with a number (1., 2., 3., etc.) were not formatting correctly (see images).

## Relevant context

![Picture1](https://github.com/modxorg/Docs/assets/152517166/8dc2d422-80d1-422a-8fd6-2b34135a6525)
![Picture2](https://github.com/modxorg/Docs/assets/152517166/cc1f3375-bf9a-41fa-911a-038a8b57ca70)

**Comment by Mark-H** [comment]
You're very lost.
