### ISSUE TITLE
Empty OpenCollective right sidebar block

### ISSUE THREAD

**Issue by ant-tar** [modxorg/Docs#519]
![2024-05-13 22 00 24](https://github.com/modxorg/Docs/assets/2815640/b17fcdcc-d392-4480-af05-430d6add6f09)

Block is empty and doesn't provide actual information about sponsors, at the same time original OC page has all the necessary information: https://opencollective.com/modx

**Comment by Mark-H** [comment]
Hm, that's odd. It's working fine on [my mirror](https://docs.modx.org/) so I'm gonna assume this is something of a cache issue. Hopefully it resolves itself shortly as I'm having some trouble again getting into the live server which is hosted/managed by our friends at Cloud.

**Comment by Jako** [comment]
Is there a domain embed restriction for the widget?

**Comment by Mark-H** [comment]
It's not really a "widget". It's just a very simple unauthenticated API we read out and store in a cache file for 2 hours. https://github.com/modxorg/DocsApp/blob/master/src/Views/Base.php#L131

Changing it from `file_get_contents()` to a request with guzzle will probably help.. guessing that Cloud changed some settings that's making that fail all of a sudden.

**Comment by Mark-H** [comment]
Working again.
