### ISSUE TITLE
Issue on extras/hybridauth/hybridauth.integrating-google

### ISSUE THREAD

**Issue by LyahMx8** [modxorg/Docs#523]
## Affected page(s)

[Please provide a link to the page(s) that have an issue, or even better, the link to the source file in the repository. For long pages, please include approximately where the problem is (heading or line numbers)](https://docs.modx.com/3.x/en/extras/hybridauth/hybridauth.integrating-google)

## What needs to be improved?

How do I implement this after setting the google key & secret?

## Relevant context

Is the problem only in a specific version or language? Then please include that.

**Comment by Mark-H** [comment]
This repository is for reporting specific issues with the documentation, for support please use the forum.
