### ISSUE TITLE
Issue on extending-modx/services/modrest

### ISSUE THREAD

**Issue by rasxod** [modxorg/Docs#526]
в документации в примере
`$client->setOption('format','JSON')`
![image](https://github.com/user-attachments/assets/c807298d-c170-41a9-a2f6-fcc9ba170f41)

либо измените пожалуйста регистр **JSON** на **json**
либо в самом слассе modrest приведите значение к заглавным для всех значений иначе не работает!

**Comment by Jako** [comment]
It would be easier to create a PR on your own instead of waiting for a another one to do that.
