### ISSUE TITLE
Incorrect table formatting on extras/renderresources/index.md

### ISSUE THREAD

**Issue by Mark-H** [modxorg/Docs#55]
## Affected page(s)

http://docs.modx.org/current/en/extras/renderresources

## What needs to be improved?

Under "Selection Properties" at the start and end of that section, there are some broken tables. 

## Relevant versions

The problem affects the following version(s): 

- [x] 2.x (current)
- [ ] 3.x

**Comment by Ibochkarev** [comment]
Fixed
