### ISSUE TITLE
Issue on /current/en/extras/collections

### ISSUE THREAD

**Issue by Ibochkarev** [modxorg/Docs#56]
### Summary
No images are displayed - instead of pictures - markup markdown

http://docs.modx.org/current/en/extras/collections

The specified image in the document is not displayed.

![image](https://user-images.githubusercontent.com/2138260/56998317-b246de00-6bcc-11e9-9ea6-c42da5a28da8.png)

**Comment by Mark-H** [comment]
Related to #22
