### ISSUE TITLE
Add MODX.com to table on extras/index.md

### ISSUE THREAD

**Issue by Mark-H** [modxorg/Docs#64]
## Affected page(s)

https://docs.modx.org/current/en/extras

## What needs to be improved?

The table lists sources, but to anyone just skimming the page they wont notice MODX.com being listed as official source before the table.

So MODX.com should be added as first row in the table. 

## Relevant context

All.

**Comment by Ibochkarev** [comment]
Add in https://github.com/modxorg/Docs/commit/c03048bda962701c03bab373456b175702abb860
