### ISSUE TITLE
Issue on getting-started/getting-started: guide new users into MODX better

### ISSUE THREAD

**Issue by Mark-H** [modxorg/Docs#76]
## Affected page(s)

http://docs.modx.org/current/en/getting-started/getting-started

## What needs to be improved?

According to the documentation, there is no default content in Revo. But there is a default resource and a very basic template now. Those should be explained (where does what come from?) in more detail. 

Ideally this page should introduce people to some of the MODX concepts and get them on their way to MODX mastery. It could link generously to other sections like the package manager, the glossary, etc.  

## Relevant context

All.

**Comment by alienbuild** [comment]
Updated here:
https://github.com/modxorg/Docs/pull/94

**Comment by Mark-H** [comment]
That does look better already :)
