### ISSUE TITLE
Home link broken on page not found: /current/en/_legacy/getting-started/roadmap

### ISSUE THREAD

**Issue by Mark-H** [modxorg/Docs#82]
## Page not found

https://docs.modx.org/current/en/_legacy/getting-started/roadmap

## Problem

Tried to find the roadmap, got on a 404, noticed that the home link does not work.

**Comment by Ibochkarev** [comment]
@Mark-H https://github.com/modxorg/Docs/commit/be8ffc1aa5fc51ead1012aaae1a26f13b6b0f8a2

**Comment by Mark-H** [comment]
Yeah, I know legacy was removed. The problem is that the logo link is wrong on a page not found response.

**Comment by Mark-H** [comment]
Fixed in modxorg/DocsApp@aa756cea84dbf4271490338c7dc1c9ff2f6f126d
