### ISSUE TITLE
Issue on getting-started/server-requirements

### ISSUE THREAD

**Issue by Ibochkarev** [modxorg/Docs#87]
## Affected page(s)

https://docs.modx.org/current/en/getting-started/server-requirements

## What needs to be improved?

This section should be rewritten because the data is outdated and the actual data is needed.

Information can be obtained from the official site https://modx.com/download

**Comment by Mark-H** [comment]
The version I did for 3.x could serve as a starting point for a simplified, improved version: https://docs.modx.org/3.x/en/getting-started/server-requirements

2.x requires PHP 5.3.3 or higher, with exceptions for 2.7.0 and 2.7.1 which require php 5.4 (but that's been fixed for 2.7.2)
